---
binding_credentials:
- name: haproxy
  plan: haproxy
  datatype: array
  value: "[JOB.haproxy.ip]"
input_mappings:
- key: keepalived.vip1
  valueformat: ip_range
  valuemap: 1:all
- key: keepalived.vip3
  valueformat: ip_range
  valuemap: 1:all
- key: keepalived.vip2
  valueformat: ip_range
  valuemap: 1:all
- key: keepalived.virtual_router_id
  valueformat: number_range
  valuemap: 2:all
- key: keepalived.priority
  valueformat: number
  valuemap: "1"
- key: keepalived.test
  valueformat: number
  valuemap: "any:all"
- key: keepalived.test
  valueformat: number
  valuemap: "any:all"
instance_groups:
- name: haproxy
  templates:
  - haproxy
    keepalived
