---
binding_credentials:
- name: haproxy
  plan: haproxy
  datatype: array
  value: "[JOB.haproxy.ip]"
input_mappings:
- key: keepalived.vip
  valueformat: ip_range
  valuemap: one_from_many
- key: keepalived.virtual_router_id
  valueformat: number_range
  valuemap: one_from_many
- key: keepalived.priority
  valueformat: number
  valuemap: one_from_one
instance_groups:
- name: haproxy
  templates:
  - haproxy
    keepalived
- name: lvs
  templates:
  - lvs
    keepalived
- name: nginx
  templates:
  - nginx
    keepalived
- name: apache
  templates:
  - apache
    keepalived
